# Generated by Django 5.0.1 on 2024-01-06 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_room_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="guest_can_pause",
        ),
        migrations.RemoveField(
            model_name="room",
            name="votes_to_skip",
        ),
    ]
