# Generated by Django 5.0.1 on 2024-01-08 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_room_guest_can_pause_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Room",
            new_name="Note",
        ),
    ]
