# Generated by Django 5.0.1 on 2024-02-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_rename_room_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="host",
            field=models.CharField(default="", max_length=50, unique=True),
        ),
    ]
